### ISSUE TITLE
Section 1 in tutorial, empty page

### ISSUE THREAD

**Issue by stevefister** [Urigo/Ionic-MeteorCLI-WhatsApp#28]
Hello, I've followed the tutorial up to just below 1.7. Upon starting the app and viewing in a web browser (running MacOS), I only get a blank page with a blank top nav - no buttons. I've checked all code is identical to the tutorial...Any ideas? Thanks.

**Comment by DAB0mB** [comment]
@stevefister I don't seem to get any error, the page looks just like in the screenshot. Can you please open the development console and tell me if there was any error thrown?

**Comment by DAB0mB** [comment]
Closing due to unresponsiveness.
